# Generated by Django 5.1.1 on 2024-10-07 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="images",
            name="users_like",
            field=models.ManyToManyField(
                blank=True,
                related_name="images_liked",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
