# Generated by Django 5.1.2 on 2024-10-24 02:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_images_users_like"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="images",
            name="total_likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="images",
            index=models.Index(
                fields=["-total_likes"], name="images_imag_total_l_6fd6e6_idx"
            ),
        ),
    ]
